"""Create initial PostgreSQL schema

Revision ID: b5af93f1af86
Revises: 
Create Date: 2025-11-04 20:52:00.839479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5af93f1af86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_config',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_key', sa.Integer(), nullable=False),
    sa.Column('chat_key_name', sa.String(), nullable=True),
    sa.Column('chat_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', 'chat_key')
    )
    op.create_table('bot_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_key', sa.BigInteger(), nullable=True),
    sa.Column('chat_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_user_chats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('dt_last', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_table('bot_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=60), nullable=True),
    sa.Column('user_type', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('admins', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('kv_store',
    sa.Column('kv_key', sa.String(), nullable=False),
    sa.Column('kv_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('kv_key')
    )
    op.create_table('mymtlwalletbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('public_key', sa.String(length=60), nullable=True),
    sa.Column('secret_key', sa.String(length=160), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('last_use_day', sa.DateTime(), nullable=True),
    sa.Column('use_pin', sa.SmallInteger(), nullable=True),
    sa.Column('free_wallet', sa.SmallInteger(), nullable=True),
    sa.Column('default_wallet', sa.SmallInteger(), nullable=True),
    sa.Column('need_delete', sa.SmallInteger(), nullable=True),
    sa.Column('last_event_id', sa.String(length=32), nullable=True),
    sa.Column('balances', sa.Text(), nullable=True),
    sa.Column('balances_event_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mymtlwalletbot_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('log_dt', sa.DateTime(), nullable=True),
    sa.Column('log_operation', sa.String(length=32), nullable=True),
    sa.Column('log_operation_info', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('t_div_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dt_pay', sa.DateTime(), nullable=False),
    sa.Column('memo', sa.String(length=60), nullable=True),
    sa.Column('pay_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_ledgers',
    sa.Column('ledger', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('ledger')
    )
    op.create_table('t_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('was_send', sa.Integer(), nullable=True),
    sa.Column('dt_add', sa.DateTime(), nullable=True),
    sa.Column('use_alarm', sa.Integer(), nullable=True),
    sa.Column('update_id', sa.BigInteger(), nullable=True),
    sa.Column('button_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_operations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=True),
    sa.Column('amount1', sa.String(length=32), nullable=True),
    sa.Column('code1', sa.String(length=64), nullable=True),
    sa.Column('amount2', sa.String(length=32), nullable=True),
    sa.Column('code2', sa.String(length=64), nullable=True),
    sa.Column('from_account', sa.String(length=64), nullable=True),
    sa.Column('for_account', sa.String(length=64), nullable=True),
    sa.Column('memo', sa.String(length=64), nullable=True),
    sa.Column('transaction_hash', sa.String(length=64), nullable=True),
    sa.Column('ledger', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['t_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_watch_list',
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('account')
    )
    op.create_table('chat_members',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('t_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_key', sa.String(length=60), nullable=True),
    sa.Column('mtl_sum', sa.Float(), nullable=True),
    sa.Column('user_calc', sa.Float(), nullable=True),
    sa.Column('user_div', sa.Float(), nullable=True),
    sa.Column('id_div_list', sa.Integer(), nullable=True),
    sa.Column('was_packed', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_div_list'], ['t_div_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_saved_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['t_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_div_list', sa.Integer(), nullable=True),
    sa.Column('xdr_id', sa.BigInteger(), nullable=True),
    sa.Column('xdr', sa.Text(), nullable=True),
    sa.Column('was_send', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_div_list'], ['t_div_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_transaction')
    op.drop_table('t_saved_messages')
    op.drop_table('t_payments')
    op.drop_table('chat_members')
    op.drop_table('t_watch_list')
    op.drop_table('t_summary')
    op.drop_table('t_operations')
    op.drop_table('t_message')
    op.drop_table('t_ledgers')
    op.drop_table('t_div_list')
    op.drop_table('mymtlwalletbot_log')
    op.drop_table('mymtlwalletbot')
    op.drop_table('kv_store')
    op.drop_table('chats')
    op.drop_table('bot_users')
    op.drop_table('bot_user_chats')
    op.drop_table('bot_table')
    op.drop_table('bot_config')
    # ### end Alembic commands ###
